### ISSUE TITLE
Display login nodes dynamically

### ISSUE THREAD

**Issue by cnweaver** [maniaclab/osgconnect-portal#1]
`view_login_nodes` needs to query the login node groups and display all of the ones which exist, instead of hard-coding a fixed set.

**Comment by jarofmy** [comment]
Should be updated to do so, although currently there are "login04" and "login05" nodes created without corresponding grafanas, so the graphs simply display "No data". Additionally, there is inconsistency with display-name and names within the metadata associated with the login nodes.

For example: 

```
{ "description": "OSG-Connect interactive job submission host 2", "display_name": "login04.osgconnect.net", "email": " ", "name": "root.osg.login-nodes.login02", "pending": false, "phone": " ", "purpose": "Resource Provider", "unix_id": 5073 }

{ "description": "OSG-Connect interactive job submission host 3", "display_name": "login05.osgconnect.net", "email": " ", "name": "root.osg.login-nodes.login03", "pending": false, "phone": " ", "purpose": "Resource Provider", "unix_id": 5074 }
```

The current solution for generating the grafana src link is by manipulating the displayname:

`grafana_src_name = display_name.split('.').join('_')`

It would be nice to have the login-nodes have their grafana names to be pulled directly from the metadata with underscores: `login04_osgconnect_net`

**Comment by jarofmy** [comment]
Ah, I see the update to the `create_login_groups.sh` script, the portal dev db must not have been restarted with the updated import.
