### ISSUE TITLE
home_text_headline is not updating

### ISSUE THREAD

**Issue by rynge** [maniaclab/osgconnect-portal#5]
This is for the osgconnect portal with the markdown source being https://github.com/opensciencegrid/osgconnect-portal-markdowns

I tried to update the headline on the mainpage but it not changing. Other things, like the home_text_rotating, do update so I think the webhook is functioning.

**Comment by cnweaver** [comment]
@jarofmy Can you take a look at what might be happening here?

**Comment by jarofmy** [comment]
@cnweaver oops, I had taken care of this issue awhile ago and forgot to comment/close. The markdown should be rendering correctly now. Although for UI purposes, I hardcoded the second part "Documentation at https://support.opensciencegrid.org" in a smaller sub-headline, to make readability a little nicer for users.
